/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link TicketAccountData}
 * @category Accounts
 * @category generated
 */
export type TicketAccountDataArgs = {
  stateAddress: web3.PublicKey
  beneficiary: web3.PublicKey
  lamportsAmount: beet.bignum
  createdEpoch: beet.bignum
}

export const ticketAccountDataDiscriminator = [133, 77, 18, 98, 211, 1, 231, 3]
/**
 * Holds the data for the {@link TicketAccountData} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class TicketAccountData implements TicketAccountDataArgs {
  private constructor(
    readonly stateAddress: web3.PublicKey,
    readonly beneficiary: web3.PublicKey,
    readonly lamportsAmount: beet.bignum,
    readonly createdEpoch: beet.bignum,
  ) {}

  /**
   * Creates a {@link TicketAccountData} instance from the provided args.
   */
  static fromArgs(args: TicketAccountDataArgs) {
    return new TicketAccountData(
      args.stateAddress,
      args.beneficiary,
      args.lamportsAmount,
      args.createdEpoch,
    )
  }

  /**
   * Deserializes the {@link TicketAccountData} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [TicketAccountData, number] {
    return TicketAccountData.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link TicketAccountData} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
  ): Promise<TicketAccountData> {
    const accountInfo = await connection.getAccountInfo(address)
    if (accountInfo == null) {
      throw new Error(`Unable to find TicketAccountData account at ${address}`)
    }
    return TicketAccountData.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Deserializes the {@link TicketAccountData} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [TicketAccountData, number] {
    return ticketAccountDataBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link TicketAccountData} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return ticketAccountDataBeet.serialize({
      accountDiscriminator: ticketAccountDataDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link TicketAccountData}
   */
  static get byteSize() {
    return ticketAccountDataBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link TicketAccountData} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      TicketAccountData.byteSize,
      commitment,
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link TicketAccountData} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === TicketAccountData.byteSize
  }

  /**
   * Returns a readable version of {@link TicketAccountData} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      stateAddress: this.stateAddress.toBase58(),
      beneficiary: this.beneficiary.toBase58(),
      lamportsAmount: (() => {
        const x = <{ toNumber: () => number }>this.lamportsAmount
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      createdEpoch: (() => {
        const x = <{ toNumber: () => number }>this.createdEpoch
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const ticketAccountDataBeet = new beet.BeetStruct<
  TicketAccountData,
  TicketAccountDataArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['stateAddress', beetSolana.publicKey],
    ['beneficiary', beetSolana.publicKey],
    ['lamportsAmount', beet.u64],
    ['createdEpoch', beet.u64],
  ],
  TicketAccountData.fromArgs,
  'TicketAccountData,',
)
