/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AddMapping
 * @category generated
 */
export const addMappingStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'AddMappingInstructionArgs',
)
/**
 * Accounts required by the _addMapping_ instruction
 *
 * @property [_writable_, **signer**] funding_account
 * @property [_writable_, **signer**] cur_mapping
 * @property [_writable_, **signer**] next_mapping
 * @category Instructions
 * @category AddMapping
 * @category generated
 */
export type AddMappingInstructionAccounts = {
  funding_account: web3.PublicKey
  cur_mapping: web3.PublicKey
  next_mapping: web3.PublicKey
}

export const AddMappingAccounts = [
  'funding_account',
  'cur_mapping',
  'next_mapping',
]

export const addMappingInstructionDiscriminator = [2, 0, 0, 0, 1, 0, 0, 0]

export type AddMappingInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _AddMapping_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category AddMapping
 * @category generated
 */
export function createAddMappingInstruction(
  accounts: AddMappingInstructionAccounts,
): AddMappingInstruction {
  const { funding_account, cur_mapping, next_mapping } = accounts

  const [data] = addMappingStruct.serialize({
    instructionDiscriminator: addMappingInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: funding_account,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: cur_mapping,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: next_mapping,
      isWritable: true,
      isSigner: true,
    },
  ]

  const ix: AddMappingInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
