/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AddPrice
 * @category generated
 */
export type AddPriceInstructionArgs = {
  expo_: number
  ptype_: number
}
/**
 * @category Instructions
 * @category AddPrice
 * @category generated
 */
export const addPriceStruct = new beet.BeetArgsStruct<
  AddPriceInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['expo_', beet.i32],
    ['ptype_', beet.u32],
  ],
  'AddPriceInstructionArgs',
)
/**
 * Accounts required by the _addPrice_ instruction
 *
 * @property [_writable_, **signer**] funding_account
 * @property [_writable_, **signer**] product_account
 * @property [_writable_, **signer**] price_account
 * @category Instructions
 * @category AddPrice
 * @category generated
 */
export type AddPriceInstructionAccounts = {
  funding_account: web3.PublicKey
  product_account: web3.PublicKey
  price_account: web3.PublicKey
}

export const AddPriceAccounts = [
  'funding_account',
  'product_account',
  'price_account',
]

export const addPriceInstructionDiscriminator = [2, 0, 0, 0, 4, 0, 0, 0]

export type AddPriceInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _AddPrice_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddPrice
 * @category generated
 */
export function createAddPriceInstruction(
  accounts: AddPriceInstructionAccounts,
  args: AddPriceInstructionArgs,
): AddPriceInstruction {
  const { funding_account, product_account, price_account } = accounts

  const [data] = addPriceStruct.serialize({
    instructionDiscriminator: addPriceInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: funding_account,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: product_account,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: price_account,
      isWritable: true,
      isSigner: true,
    },
  ]

  const ix: AddPriceInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
