/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * @category Instructions
 * @category AddPublisher
 * @category generated
 */
export type AddPublisherInstructionArgs = {
  pub_: web3.PublicKey
}
/**
 * @category Instructions
 * @category AddPublisher
 * @category generated
 */
export const addPublisherStruct = new beet.BeetArgsStruct<
  AddPublisherInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['pub_', beetSolana.publicKey],
  ],
  'AddPublisherInstructionArgs',
)
/**
 * Accounts required by the _addPublisher_ instruction
 *
 * @property [_writable_, **signer**] funding_account
 * @property [_writable_, **signer**] price_account
 * @category Instructions
 * @category AddPublisher
 * @category generated
 */
export type AddPublisherInstructionAccounts = {
  funding_account: web3.PublicKey
  price_account: web3.PublicKey
}

export const AddPublisherAccounts = ['funding_account', 'price_account']

export const addPublisherInstructionDiscriminator = [2, 0, 0, 0, 5, 0, 0, 0]

export type AddPublisherInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _AddPublisher_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddPublisher
 * @category generated
 */
export function createAddPublisherInstruction(
  accounts: AddPublisherInstructionAccounts,
  args: AddPublisherInstructionArgs,
): AddPublisherInstruction {
  const { funding_account, price_account } = accounts

  const [data] = addPublisherStruct.serialize({
    instructionDiscriminator: addPublisherInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: funding_account,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: price_account,
      isWritable: true,
      isSigner: true,
    },
  ]

  const ix: AddPublisherInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
