/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AddProduct
 * @category generated
 */
export const addProductStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'AddProductInstructionArgs',
)
/**
 * Accounts required by the _addProduct_ instruction
 *
 * @property [_writable_, **signer**] funding_account
 * @property [_writable_, **signer**] tail_mapping_account
 * @property [_writable_, **signer**] new_product_account
 * @category Instructions
 * @category AddProduct
 * @category generated
 */
export type AddProductInstructionAccounts = {
  funding_account: web3.PublicKey
  tail_mapping_account: web3.PublicKey
  new_product_account: web3.PublicKey
}

export const AddProductAccounts = [
  'funding_account',
  'tail_mapping_account',
  'new_product_account',
]

export const addProductInstructionDiscriminator = [2, 0, 0, 0, 2, 0, 0, 0]

export type AddProductInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _AddProduct_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category AddProduct
 * @category generated
 */
export function createAddProductInstruction(
  accounts: AddProductInstructionAccounts,
): AddProductInstruction {
  const { funding_account, tail_mapping_account, new_product_account } =
    accounts

  const [data] = addProductStruct.serialize({
    instructionDiscriminator: addProductInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: funding_account,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: tail_mapping_account,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: new_product_account,
      isWritable: true,
      isSigner: true,
    },
  ]

  const ix: AddProductInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
