/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ResizeAccount
 * @category generated
 */
export const resizeAccountStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ResizeAccountInstructionArgs',
)
/**
 * Accounts required by the _resizeAccount_ instruction
 *
 * @property [_writable_, **signer**] funding_account
 * @property [_writable_, **signer**] price_account
 * @category Instructions
 * @category ResizeAccount
 * @category generated
 */
export type ResizeAccountInstructionAccounts = {
  funding_account: web3.PublicKey
  price_account: web3.PublicKey
}

export const ResizeAccountAccounts = ['funding_account', 'price_account']

export const resizeAccountInstructionDiscriminator = [2, 0, 0, 0, 14, 0, 0, 0]

export type ResizeAccountInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _ResizeAccount_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ResizeAccount
 * @category generated
 */
export function createResizeAccountInstruction(
  accounts: ResizeAccountInstructionAccounts,
): ResizeAccountInstruction {
  const { funding_account, price_account } = accounts

  const [data] = resizeAccountStruct.serialize({
    instructionDiscriminator: resizeAccountInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: funding_account,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: price_account,
      isWritable: true,
      isSigner: true,
    },
  ]

  const ix: ResizeAccountInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
