/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category SetMinPub
 * @category generated
 */
export type SetMinPubInstructionArgs = {
  min_pub_: number
}
/**
 * @category Instructions
 * @category SetMinPub
 * @category generated
 */
export const setMinPubStruct = new beet.BeetArgsStruct<
  SetMinPubInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['min_pub_', beet.u8],
  ],
  'SetMinPubInstructionArgs',
)
/**
 * Accounts required by the _setMinPub_ instruction
 *
 * @property [_writable_, **signer**] funding_account
 * @property [_writable_, **signer**] price_account
 * @category Instructions
 * @category SetMinPub
 * @category generated
 */
export type SetMinPubInstructionAccounts = {
  funding_account: web3.PublicKey
  price_account: web3.PublicKey
}

export const SetMinPubAccounts = ['funding_account', 'price_account']

export const setMinPubInstructionDiscriminator = [2, 0, 0, 0, 12, 0, 0, 0]

export type SetMinPubInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _SetMinPub_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SetMinPub
 * @category generated
 */
export function createSetMinPubInstruction(
  accounts: SetMinPubInstructionAccounts,
  args: SetMinPubInstructionArgs,
): SetMinPubInstruction {
  const { funding_account, price_account } = accounts

  const [data] = setMinPubStruct.serialize({
    instructionDiscriminator: setMinPubInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: funding_account,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: price_account,
      isWritable: true,
      isSigner: true,
    },
  ]

  const ix: SetMinPubInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
