/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category UpdProduct
 * @category generated
 */
export type UpdProductInstructionArgs = {
  new_data: Uint8Array
}
/**
 * @category Instructions
 * @category UpdProduct
 * @category generated
 */
export const updProductStruct = new beet.FixableBeetArgsStruct<
  UpdProductInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['new_data', beet.bytes],
  ],
  'UpdProductInstructionArgs',
)
/**
 * Accounts required by the _updProduct_ instruction
 *
 * @property [_writable_, **signer**] funding_account
 * @property [_writable_, **signer**] product_account
 * @category Instructions
 * @category UpdProduct
 * @category generated
 */
export type UpdProductInstructionAccounts = {
  funding_account: web3.PublicKey
  product_account: web3.PublicKey
}

export const UpdProductAccounts = ['funding_account', 'product_account']

export const updProductInstructionDiscriminator = [2, 0, 0, 0, 3, 0, 0, 0]

export type UpdProductInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _UpdProduct_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdProduct
 * @category generated
 */
export function createUpdProductInstruction(
  accounts: UpdProductInstructionAccounts,
  args: UpdProductInstructionArgs,
): UpdProductInstruction {
  const { funding_account, product_account } = accounts

  const [data] = updProductStruct.serialize({
    instructionDiscriminator: updProductInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: funding_account,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: product_account,
      isWritable: true,
      isSigner: true,
    },
  ]

  const ix: UpdProductInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
