/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type AccountHeader = {
  magic: number
  version: number
  type: number
  size: number
}

/**
 * @category userTypes
 * @category generated
 */
export const accountHeaderBeet = new beet.BeetArgsStruct<AccountHeader>(
  [
    ['magic', beet.u32],
    ['version', beet.u32],
    ['type', beet.u32],
    ['size', beet.u32],
  ],
  'AccountHeader',
)
