/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'
import { PriceInfo, priceInfoBeet } from './PriceInfo.js'
export type PriceComponent = {
  publisher: web3.PublicKey
  aggregate: PriceInfo
  latest: PriceInfo
}

/**
 * @category userTypes
 * @category generated
 */
export const priceComponentBeet = new beet.BeetArgsStruct<PriceComponent>(
  [
    ['publisher', beetSolana.publicKey],
    ['aggregate', priceInfoBeet],
    ['latest', priceInfoBeet],
  ],
  'PriceComponent',
)
