/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type PriceEma = {
  valueComponent: beet.bignum
  value: number
  numerator: beet.bignum
  denominator: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const priceEmaBeet = new beet.BeetArgsStruct<PriceEma>(
  [
    ['valueComponent', beet.i64],
    ['value', beet.u32],
    ['numerator', beet.i64],
    ['denominator', beet.i64],
  ],
  'PriceEma',
)
