/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type PriceInfo = {
  priceComponent: beet.bignum
  price: beet.bignum
  confidenceComponent: number
  confidence: number
  publishSlot: beet.bignum
  corporateAction: number
  status: number
}

/**
 * @category userTypes
 * @category generated
 */
export const priceInfoBeet = new beet.BeetArgsStruct<PriceInfo>(
  [
    ['priceComponent', beet.i64],
    ['price', beet.u64],
    ['confidenceComponent', beet.u32],
    ['confidence', beet.u32],
    ['publishSlot', beet.u64],
    ['corporateAction', beet.u32],
    ['status', beet.u32],
  ],
  'PriceInfo',
)
