/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type Product = {
  symbol: string
  assetType: string
  quoteCurrency: string
  tenor: string
  priceAccount: string
  index: string
}

/**
 * @category userTypes
 * @category generated
 */
export const productBeet = new beet.FixableBeetArgsStruct<Product>(
  [
    ['symbol', beet.utf8String],
    ['assetType', beet.utf8String],
    ['quoteCurrency', beet.utf8String],
    ['tenor', beet.utf8String],
    ['priceAccount', beet.utf8String],
    ['index', beet.utf8String],
  ],
  'Product',
)
