/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
export type ChangeAuthorityData = {
  admin: beet.COption<web3.PublicKey>
  validatorManager: beet.COption<web3.PublicKey>
  operationalSolAccount: beet.COption<web3.PublicKey>
  treasuryMsolAccount: beet.COption<web3.PublicKey>
}

/**
 * @category userTypes
 * @category generated
 */
export const changeAuthorityDataBeet =
  new beet.FixableBeetArgsStruct<ChangeAuthorityData>(
    [
      ['admin', beet.coption(beetSolana.publicKey)],
      ['validatorManager', beet.coption(beetSolana.publicKey)],
      ['operationalSolAccount', beet.coption(beetSolana.publicKey)],
      ['treasuryMsolAccount', beet.coption(beetSolana.publicKey)],
    ],
    'ChangeAuthorityData',
  )
