/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import { Fee, feeBeet } from './Fee.js'
export type LiqPool = {
  lpMint: web3.PublicKey
  lpMintAuthorityBumpSeed: number
  solLegBumpSeed: number
  msolLegAuthorityBumpSeed: number
  msolLeg: web3.PublicKey
  lpLiquidityTarget: beet.bignum
  lpMaxFee: Fee
  lpMinFee: Fee
  treasuryCut: Fee
  lpSupply: beet.bignum
  lentFromSolLeg: beet.bignum
  liquiditySolCap: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const liqPoolBeet = new beet.BeetArgsStruct<LiqPool>(
  [
    ['lpMint', beetSolana.publicKey],
    ['lpMintAuthorityBumpSeed', beet.u8],
    ['solLegBumpSeed', beet.u8],
    ['msolLegAuthorityBumpSeed', beet.u8],
    ['msolLeg', beetSolana.publicKey],
    ['lpLiquidityTarget', beet.u64],
    ['lpMaxFee', feeBeet],
    ['lpMinFee', feeBeet],
    ['treasuryCut', feeBeet],
    ['lpSupply', beet.u64],
    ['lentFromSolLeg', beet.u64],
    ['liquiditySolCap', beet.u64],
  ],
  'LiqPool',
)
