/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { Fee, feeBeet } from './Fee.js'
export type LiqPoolInitializeData = {
  lpLiquidityTarget: beet.bignum
  lpMaxFee: Fee
  lpMinFee: Fee
  lpTreasuryCut: Fee
}

/**
 * @category userTypes
 * @category generated
 */
export const liqPoolInitializeDataBeet =
  new beet.BeetArgsStruct<LiqPoolInitializeData>(
    [
      ['lpLiquidityTarget', beet.u64],
      ['lpMaxFee', feeBeet],
      ['lpMinFee', feeBeet],
      ['lpTreasuryCut', feeBeet],
    ],
    'LiqPoolInitializeData',
  )
