/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'
export type List = {
  account: web3.PublicKey
  itemSize: number
  count: number
  newAccount: web3.PublicKey
  copiedCount: number
}

/**
 * @category userTypes
 * @category generated
 */
export const listBeet = new beet.BeetArgsStruct<List>(
  [
    ['account', beetSolana.publicKey],
    ['itemSize', beet.u32],
    ['count', beet.u32],
    ['newAccount', beetSolana.publicKey],
    ['copiedCount', beet.u32],
  ],
  'List',
)
