/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
export type ValidatorRecord = {
  validatorAccount: web3.PublicKey
  activeBalance: beet.bignum
  score: number
  lastStakeDeltaEpoch: beet.bignum
  duplicationFlagBumpSeed: number
}

/**
 * @category userTypes
 * @category generated
 */
export const validatorRecordBeet = new beet.BeetArgsStruct<ValidatorRecord>(
  [
    ['validatorAccount', beetSolana.publicKey],
    ['activeBalance', beet.u64],
    ['score', beet.u32],
    ['lastStakeDeltaEpoch', beet.u64],
    ['duplicationFlagBumpSeed', beet.u8],
  ],
  'ValidatorRecord',
)
