/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import { List, listBeet } from './List.js'
export type ValidatorSystem = {
  validatorList: List
  managerAuthority: web3.PublicKey
  totalValidatorScore: number
  totalActiveBalance: beet.bignum
  autoAddValidatorEnabled: number
}

/**
 * @category userTypes
 * @category generated
 */
export const validatorSystemBeet = new beet.BeetArgsStruct<ValidatorSystem>(
  [
    ['validatorList', listBeet],
    ['managerAuthority', beetSolana.publicKey],
    ['totalValidatorScore', beet.u32],
    ['totalActiveBalance', beet.u64],
    ['autoAddValidatorEnabled', beet.u8],
  ],
  'ValidatorSystem',
)
