/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type Bumps = {
  bump: number
  mintBump: number
  metadataBump: number
}

/**
 * @category userTypes
 * @category generated
 */
export const bumpsBeet = new beet.BeetArgsStruct<Bumps>(
  [
    ['bump', beet.u8],
    ['mintBump', beet.u8],
    ['metadataBump', beet.u8],
  ],
  'Bumps',
)
