/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
export type SellerConfig = {
  refundTimespan: beet.bignum
  price: number
  acceptedMint: web3.PublicKey
  exemplars: number
}

/**
 * @category userTypes
 * @category generated
 */
export const sellerConfigBeet = new beet.BeetArgsStruct<SellerConfig>(
  [
    ['refundTimespan', beet.u64],
    ['price', beet.u32],
    ['acceptedMint', beetSolana.publicKey],
    ['exemplars', beet.i32],
  ],
  'SellerConfig',
)
