/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category BuyToken
 * @category generated
 */
export type BuyTokenInstructionArgs = {
  timestamp: beet.bignum
}
/**
 * @category Instructions
 * @category BuyToken
 * @category generated
 */
export const buyTokenStruct = new beet.BeetArgsStruct<
  BuyTokenInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['timestamp', beet.u64],
  ],
  'BuyTokenInstructionArgs',
)
/**
 * Accounts required by the _buyToken_ instruction
 *
 * @property [] associatedTokenProgram
 * @property [] clock
 * @property [_writable_, **signer**] authority
 * @property [_writable_] token
 * @property [_writable_] tokenMint
 * @property [_writable_] buyerTransferVault
 * @property [] acceptedMint
 * @property [_writable_] payment
 * @property [_writable_] paymentVault
 * @property [_writable_] buyerTokenVault
 * @category Instructions
 * @category BuyToken
 * @category generated
 */
export type BuyTokenInstructionAccounts = {
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  rent?: web3.PublicKey
  clock: web3.PublicKey
  authority: web3.PublicKey
  token: web3.PublicKey
  tokenMint: web3.PublicKey
  buyerTransferVault: web3.PublicKey
  acceptedMint: web3.PublicKey
  payment: web3.PublicKey
  paymentVault: web3.PublicKey
  buyerTokenVault: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const buyTokenInstructionDiscriminator = [
  138, 127, 14, 91, 38, 87, 115, 105,
]

/**
 * Creates a _BuyToken_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category BuyToken
 * @category generated
 */
export function createBuyTokenInstruction(
  accounts: BuyTokenInstructionAccounts,
  args: BuyTokenInstructionArgs,
  programId = new web3.PublicKey(
    'BrickarF2QeREBZsapbhgYPHJi5FYkJVnx7mZhxETCt5',
  ),
) {
  const [data] = buyTokenStruct.serialize({
    instructionDiscriminator: buyTokenInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clock,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.token,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerTransferVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.acceptedMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payment,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.paymentVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerTokenVault,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
