/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category Deletetoken
 * @category generated
 */
export const deletetokenStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'DeletetokenInstructionArgs',
)
/**
 * Accounts required by the _deletetoken_ instruction
 *
 * @property [_writable_, **signer**] authority
 * @property [_writable_] token
 * @category Instructions
 * @category Deletetoken
 * @category generated
 */
export type DeletetokenInstructionAccounts = {
  authority: web3.PublicKey
  token: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const deletetokenInstructionDiscriminator = [
  144, 227, 92, 140, 137, 31, 96, 86,
]

/**
 * Creates a _Deletetoken_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category Deletetoken
 * @category generated
 */
export function createDeletetokenInstruction(
  accounts: DeletetokenInstructionAccounts,
  programId = new web3.PublicKey(
    'BrickarF2QeREBZsapbhgYPHJi5FYkJVnx7mZhxETCt5',
  ),
) {
  const [data] = deletetokenStruct.serialize({
    instructionDiscriminator: deletetokenInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.token,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
