/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category EditTokenPrice
 * @category generated
 */
export type EditTokenPriceInstructionArgs = {
  tokenPrice: number
}
/**
 * @category Instructions
 * @category EditTokenPrice
 * @category generated
 */
export const editTokenPriceStruct = new beet.BeetArgsStruct<
  EditTokenPriceInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['tokenPrice', beet.u32],
  ],
  'EditTokenPriceInstructionArgs',
)
/**
 * Accounts required by the _editTokenPrice_ instruction
 *
 * @property [_writable_, **signer**] authority
 * @property [_writable_] token
 * @category Instructions
 * @category EditTokenPrice
 * @category generated
 */
export type EditTokenPriceInstructionAccounts = {
  authority: web3.PublicKey
  token: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const editTokenPriceInstructionDiscriminator = [
  197, 30, 108, 1, 210, 189, 181, 237,
]

/**
 * Creates a _EditTokenPrice_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category EditTokenPrice
 * @category generated
 */
export function createEditTokenPriceInstruction(
  accounts: EditTokenPriceInstructionAccounts,
  args: EditTokenPriceInstructionArgs,
  programId = new web3.PublicKey(
    'BrickarF2QeREBZsapbhgYPHJi5FYkJVnx7mZhxETCt5',
  ),
) {
  const [data] = editTokenPriceStruct.serialize({
    instructionDiscriminator: editTokenPriceInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.token,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
