/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * Arguments used to create {@link App}
 * @category Accounts
 * @category generated
 */
export type AppArgs = {
  authority: web3.PublicKey
  feeBasisPoints: number
  bump: number
  appName: string
}

export const appDiscriminator = [67, 135, 84, 79, 153, 49, 239, 169]
/**
 * Holds the data for the {@link App} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class App implements AppArgs {
  private constructor(
    readonly authority: web3.PublicKey,
    readonly feeBasisPoints: number,
    readonly bump: number,
    readonly appName: string,
  ) {}

  /**
   * Creates a {@link App} instance from the provided args.
   */
  static fromArgs(args: AppArgs) {
    return new App(args.authority, args.feeBasisPoints, args.bump, args.appName)
  }

  /**
   * Deserializes the {@link App} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [App, number] {
    return App.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link App} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<App> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find App account at ${address}`)
    }
    return App.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'BrickarF2QeREBZsapbhgYPHJi5FYkJVnx7mZhxETCt5',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, appBeet)
  }

  /**
   * Deserializes the {@link App} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [App, number] {
    return appBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link App} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return appBeet.serialize({
      accountDiscriminator: appDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link App} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: AppArgs) {
    const instance = App.fromArgs(args)
    return appBeet.toFixedFromValue({
      accountDiscriminator: appDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link App} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: AppArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      App.byteSize(args),
      commitment,
    )
  }

  /**
   * Returns a readable version of {@link App} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      authority: this.authority.toBase58(),
      feeBasisPoints: this.feeBasisPoints,
      bump: this.bump,
      appName: this.appName,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const appBeet = new beet.FixableBeetStruct<
  App,
  AppArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['authority', beetSolana.publicKey],
    ['feeBasisPoints', beet.u16],
    ['bump', beet.u8],
    ['appName', beet.utf8String],
  ],
  App.fromArgs,
  'App',
)
