/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AddLiquidity
 * @category generated
 */
export type AddLiquidityInstructionArgs = {
  lamports: beet.bignum
}
/**
 * @category Instructions
 * @category AddLiquidity
 * @category generated
 */
export const addLiquidityStruct = new beet.BeetArgsStruct<
  AddLiquidityInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['lamports', beet.u64],
  ],
  'AddLiquidityInstructionArgs',
)
/**
 * Accounts required by the _addLiquidity_ instruction
 *
 * @property [_writable_] state
 * @property [_writable_] lpMint
 * @property [] lpMintAuthority
 * @property [] liqPoolMsolLeg
 * @property [_writable_] liqPoolSolLegPda
 * @property [_writable_, **signer**] transferFrom
 * @property [_writable_] mintTo
 * @category Instructions
 * @category AddLiquidity
 * @category generated
 */
export type AddLiquidityInstructionAccounts = {
  state: web3.PublicKey
  lpMint: web3.PublicKey
  lpMintAuthority: web3.PublicKey
  liqPoolMsolLeg: web3.PublicKey
  liqPoolSolLegPda: web3.PublicKey
  transferFrom: web3.PublicKey
  mintTo: web3.PublicKey
}

export const AddLiquidityAccounts = [
  'state',
  'lpMint',
  'lpMintAuthority',
  'liqPoolMsolLeg',
  'liqPoolSolLegPda',
  'transferFrom',
  'mintTo',
]

export const addLiquidityInstructionDiscriminator = [
  181, 157, 89, 67, 143, 182, 52, 72,
]

export type AddLiquidityInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _AddLiquidity_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddLiquidity
 * @category generated
 */
export function createAddLiquidityInstruction(
  accounts: AddLiquidityInstructionAccounts,
  args: AddLiquidityInstructionArgs,
): AddLiquidityInstruction {
  const {
    state,
    lpMint,
    lpMintAuthority,
    liqPoolMsolLeg,
    liqPoolSolLegPda,
    transferFrom,
    mintTo,
  } = accounts

  const [data] = addLiquidityStruct.serialize({
    instructionDiscriminator: addLiquidityInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: lpMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: lpMintAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: liqPoolMsolLeg,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: liqPoolSolLegPda,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: transferFrom,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: mintTo,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix: AddLiquidityInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
