/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  ChangeAuthorityData,
  changeAuthorityDataBeet,
} from '../types/ChangeAuthorityData.js'

/**
 * @category Instructions
 * @category ChangeAuthority
 * @category generated
 */
export type ChangeAuthorityInstructionArgs = {
  data: ChangeAuthorityData
}
/**
 * @category Instructions
 * @category ChangeAuthority
 * @category generated
 */
export const changeAuthorityStruct = new beet.FixableBeetArgsStruct<
  ChangeAuthorityInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['data', changeAuthorityDataBeet],
  ],
  'ChangeAuthorityInstructionArgs',
)
/**
 * Accounts required by the _changeAuthority_ instruction
 *
 * @property [_writable_] state
 * @property [**signer**] adminAuthority
 * @category Instructions
 * @category ChangeAuthority
 * @category generated
 */
export type ChangeAuthorityInstructionAccounts = {
  state: web3.PublicKey
  adminAuthority: web3.PublicKey
}

export const ChangeAuthorityAccounts = ['state', 'adminAuthority']

export const changeAuthorityInstructionDiscriminator = [
  50, 106, 66, 104, 99, 118, 145, 88,
]

export type ChangeAuthorityInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _ChangeAuthority_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ChangeAuthority
 * @category generated
 */
export function createChangeAuthorityInstruction(
  accounts: ChangeAuthorityInstructionAccounts,
  args: ChangeAuthorityInstructionArgs,
): ChangeAuthorityInstruction {
  const { state, adminAuthority } = accounts

  const [data] = changeAuthorityStruct.serialize({
    instructionDiscriminator: changeAuthorityInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: adminAuthority,
      isWritable: false,
      isSigner: true,
    },
  ]

  const ix: ChangeAuthorityInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
