/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ConfigValidatorSystem
 * @category generated
 */
export type ConfigValidatorSystemInstructionArgs = {
  extraRuns: number
}
/**
 * @category Instructions
 * @category ConfigValidatorSystem
 * @category generated
 */
export const configValidatorSystemStruct = new beet.BeetArgsStruct<
  ConfigValidatorSystemInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['extraRuns', beet.u32],
  ],
  'ConfigValidatorSystemInstructionArgs',
)
/**
 * Accounts required by the _configValidatorSystem_ instruction
 *
 * @property [_writable_] state
 * @property [**signer**] managerAuthority
 * @category Instructions
 * @category ConfigValidatorSystem
 * @category generated
 */
export type ConfigValidatorSystemInstructionAccounts = {
  state: web3.PublicKey
  managerAuthority: web3.PublicKey
}

export const ConfigValidatorSystemAccounts = ['state', 'managerAuthority']

export const configValidatorSystemInstructionDiscriminator = [
  27, 90, 97, 209, 17, 115, 7, 40,
]

export type ConfigValidatorSystemInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _ConfigValidatorSystem_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ConfigValidatorSystem
 * @category generated
 */
export function createConfigValidatorSystemInstruction(
  accounts: ConfigValidatorSystemInstructionAccounts,
  args: ConfigValidatorSystemInstructionArgs,
): ConfigValidatorSystemInstruction {
  const { state, managerAuthority } = accounts

  const [data] = configValidatorSystemStruct.serialize({
    instructionDiscriminator: configValidatorSystemInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: managerAuthority,
      isWritable: false,
      isSigner: true,
    },
  ]

  const ix: ConfigValidatorSystemInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
