/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category EmergencyUnstake
 * @category generated
 */
export type EmergencyUnstakeInstructionArgs = {
  stakeIndex: number
  validatorIndex: number
}
/**
 * @category Instructions
 * @category EmergencyUnstake
 * @category generated
 */
export const emergencyUnstakeStruct = new beet.BeetArgsStruct<
  EmergencyUnstakeInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['stakeIndex', beet.u32],
    ['validatorIndex', beet.u32],
  ],
  'EmergencyUnstakeInstructionArgs',
)
/**
 * Accounts required by the _emergencyUnstake_ instruction
 *
 * @property [_writable_] state
 * @property [**signer**] validatorManagerAuthority
 * @property [_writable_] validatorList
 * @property [_writable_] stakeList
 * @property [_writable_] stakeAccount
 * @property [] stakeDepositAuthority
 * @property [] clock
 * @property [] stakeProgram
 * @category Instructions
 * @category EmergencyUnstake
 * @category generated
 */
export type EmergencyUnstakeInstructionAccounts = {
  state: web3.PublicKey
  validatorManagerAuthority: web3.PublicKey
  validatorList: web3.PublicKey
  stakeList: web3.PublicKey
  stakeAccount: web3.PublicKey
  stakeDepositAuthority: web3.PublicKey
  clock: web3.PublicKey
  stakeProgram: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const emergencyUnstakeInstructionDiscriminator = [
  123, 69, 168, 195, 183, 213, 199, 214,
]

/**
 * Creates a _EmergencyUnstake_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category EmergencyUnstake
 * @category generated
 */
export function createEmergencyUnstakeInstruction(
  accounts: EmergencyUnstakeInstructionAccounts,
  args: EmergencyUnstakeInstructionArgs,
  programId = new web3.PublicKey('MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD'),
) {
  const [data] = emergencyUnstakeStruct.serialize({
    instructionDiscriminator: emergencyUnstakeInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.validatorManagerAuthority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.validatorList,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.stakeList,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.stakeAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.stakeDepositAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clock,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.stakeProgram,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
