/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category EmergencyUnstake
 * @category generated
 */
export type EmergencyUnstakeInstructionArgs = {
  stakeIndex: number
  validatorIndex: number
}
/**
 * @category Instructions
 * @category EmergencyUnstake
 * @category generated
 */
export const emergencyUnstakeStruct = new beet.BeetArgsStruct<
  EmergencyUnstakeInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['stakeIndex', beet.u32],
    ['validatorIndex', beet.u32],
  ],
  'EmergencyUnstakeInstructionArgs',
)
/**
 * Accounts required by the _emergencyUnstake_ instruction
 *
 * @property [_writable_] state
 * @property [**signer**] validatorManagerAuthority
 * @property [_writable_] validatorList
 * @property [_writable_] stakeList
 * @property [_writable_] stakeAccount
 * @property [] stakeDepositAuthority
 * @property [] clock
 * @property [] stakeProgram
 * @category Instructions
 * @category EmergencyUnstake
 * @category generated
 */
export type EmergencyUnstakeInstructionAccounts = {
  state: web3.PublicKey
  validatorManagerAuthority: web3.PublicKey
  validatorList: web3.PublicKey
  stakeList: web3.PublicKey
  stakeAccount: web3.PublicKey
  stakeDepositAuthority: web3.PublicKey
  clock: web3.PublicKey
  stakeProgram: web3.PublicKey
}

export const EmergencyUnstakeAccounts = [
  'state',
  'validatorManagerAuthority',
  'validatorList',
  'stakeList',
  'stakeAccount',
  'stakeDepositAuthority',
  'clock',
  'stakeProgram',
]

export const emergencyUnstakeInstructionDiscriminator = [
  123, 69, 168, 195, 183, 213, 199, 214,
]

export type EmergencyUnstakeInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _EmergencyUnstake_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category EmergencyUnstake
 * @category generated
 */
export function createEmergencyUnstakeInstruction(
  accounts: EmergencyUnstakeInstructionAccounts,
  args: EmergencyUnstakeInstructionArgs,
): EmergencyUnstakeInstruction {
  const {
    state,
    validatorManagerAuthority,
    validatorList,
    stakeList,
    stakeAccount,
    stakeDepositAuthority,
    clock,
    stakeProgram,
  } = accounts

  const [data] = emergencyUnstakeStruct.serialize({
    instructionDiscriminator: emergencyUnstakeInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: validatorManagerAuthority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: validatorList,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: stakeList,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: stakeAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: stakeDepositAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: clock,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: stakeProgram,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix: EmergencyUnstakeInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
