/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category OrderUnstake
 * @category generated
 */
export type OrderUnstakeInstructionArgs = {
  msolAmount: beet.bignum
}
/**
 * @category Instructions
 * @category OrderUnstake
 * @category generated
 */
export const orderUnstakeStruct = new beet.BeetArgsStruct<
  OrderUnstakeInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['msolAmount', beet.u64],
  ],
  'OrderUnstakeInstructionArgs',
)
/**
 * Accounts required by the _orderUnstake_ instruction
 *
 * @property [_writable_] state
 * @property [_writable_] msolMint
 * @property [_writable_] burnMsolFrom
 * @property [**signer**] burnMsolAuthority
 * @property [_writable_] newTicketAccount
 * @property [] clock
 * @category Instructions
 * @category OrderUnstake
 * @category generated
 */
export type OrderUnstakeInstructionAccounts = {
  state: web3.PublicKey
  msolMint: web3.PublicKey
  burnMsolFrom: web3.PublicKey
  burnMsolAuthority: web3.PublicKey
  newTicketAccount: web3.PublicKey
  clock: web3.PublicKey
  rent?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const orderUnstakeInstructionDiscriminator = [
  97, 167, 144, 107, 117, 190, 128, 36,
]

/**
 * Creates a _OrderUnstake_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category OrderUnstake
 * @category generated
 */
export function createOrderUnstakeInstruction(
  accounts: OrderUnstakeInstructionAccounts,
  args: OrderUnstakeInstructionArgs,
  programId = new web3.PublicKey('MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD'),
) {
  const [data] = orderUnstakeStruct.serialize({
    instructionDiscriminator: orderUnstakeInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.msolMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.burnMsolFrom,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.burnMsolAuthority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.newTicketAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.clock,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
