/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * @category Instructions
 * @category RemoveValidator
 * @category generated
 */
export type RemoveValidatorInstructionArgs = {
  index: number
  validatorVote: web3.PublicKey
}
/**
 * @category Instructions
 * @category RemoveValidator
 * @category generated
 */
export const removeValidatorStruct = new beet.BeetArgsStruct<
  RemoveValidatorInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['index', beet.u32],
    ['validatorVote', beetSolana.publicKey],
  ],
  'RemoveValidatorInstructionArgs',
)
/**
 * Accounts required by the _removeValidator_ instruction
 *
 * @property [_writable_] state
 * @property [**signer**] managerAuthority
 * @property [_writable_] validatorList
 * @property [_writable_] duplicationFlag
 * @property [_writable_] operationalSolAccount
 * @category Instructions
 * @category RemoveValidator
 * @category generated
 */
export type RemoveValidatorInstructionAccounts = {
  state: web3.PublicKey
  managerAuthority: web3.PublicKey
  validatorList: web3.PublicKey
  duplicationFlag: web3.PublicKey
  operationalSolAccount: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const removeValidatorInstructionDiscriminator = [
  25, 96, 211, 155, 161, 14, 168, 188,
]

/**
 * Creates a _RemoveValidator_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RemoveValidator
 * @category generated
 */
export function createRemoveValidatorInstruction(
  accounts: RemoveValidatorInstructionAccounts,
  args: RemoveValidatorInstructionArgs,
  programId = new web3.PublicKey('MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD'),
) {
  const [data] = removeValidatorStruct.serialize({
    instructionDiscriminator: removeValidatorInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.managerAuthority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.validatorList,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.duplicationFlag,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.operationalSolAccount,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
