/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * @category Instructions
 * @category RemoveValidator
 * @category generated
 */
export type RemoveValidatorInstructionArgs = {
  index: number
  validatorVote: web3.PublicKey
}
/**
 * @category Instructions
 * @category RemoveValidator
 * @category generated
 */
export const removeValidatorStruct = new beet.BeetArgsStruct<
  RemoveValidatorInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['index', beet.u32],
    ['validatorVote', beetSolana.publicKey],
  ],
  'RemoveValidatorInstructionArgs',
)
/**
 * Accounts required by the _removeValidator_ instruction
 *
 * @property [_writable_] state
 * @property [**signer**] managerAuthority
 * @property [_writable_] validatorList
 * @property [_writable_] duplicationFlag
 * @property [_writable_] operationalSolAccount
 * @category Instructions
 * @category RemoveValidator
 * @category generated
 */
export type RemoveValidatorInstructionAccounts = {
  state: web3.PublicKey
  managerAuthority: web3.PublicKey
  validatorList: web3.PublicKey
  duplicationFlag: web3.PublicKey
  operationalSolAccount: web3.PublicKey
}

export const RemoveValidatorAccounts = [
  'state',
  'managerAuthority',
  'validatorList',
  'duplicationFlag',
  'operationalSolAccount',
]

export const removeValidatorInstructionDiscriminator = [
  25, 96, 211, 155, 161, 14, 168, 188,
]

export type RemoveValidatorInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _RemoveValidator_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RemoveValidator
 * @category generated
 */
export function createRemoveValidatorInstruction(
  accounts: RemoveValidatorInstructionAccounts,
  args: RemoveValidatorInstructionArgs,
): RemoveValidatorInstruction {
  const {
    state,
    managerAuthority,
    validatorList,
    duplicationFlag,
    operationalSolAccount,
  } = accounts

  const [data] = removeValidatorStruct.serialize({
    instructionDiscriminator: removeValidatorInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: managerAuthority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: validatorList,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: duplicationFlag,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: operationalSolAccount,
      isWritable: true,
      isSigner: false,
    },
  ]

  const ix: RemoveValidatorInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
