/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * @category Instructions
 * @category SetValidatorScore
 * @category generated
 */
export type SetValidatorScoreInstructionArgs = {
  index: number
  validatorVote: web3.PublicKey
  score: number
}
/**
 * @category Instructions
 * @category SetValidatorScore
 * @category generated
 */
export const setValidatorScoreStruct = new beet.BeetArgsStruct<
  SetValidatorScoreInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['index', beet.u32],
    ['validatorVote', beetSolana.publicKey],
    ['score', beet.u32],
  ],
  'SetValidatorScoreInstructionArgs',
)
/**
 * Accounts required by the _setValidatorScore_ instruction
 *
 * @property [_writable_] state
 * @property [**signer**] managerAuthority
 * @property [_writable_] validatorList
 * @category Instructions
 * @category SetValidatorScore
 * @category generated
 */
export type SetValidatorScoreInstructionAccounts = {
  state: web3.PublicKey
  managerAuthority: web3.PublicKey
  validatorList: web3.PublicKey
}

export const SetValidatorScoreAccounts = [
  'state',
  'managerAuthority',
  'validatorList',
]

export const setValidatorScoreInstructionDiscriminator = [
  101, 41, 206, 33, 216, 111, 25, 78,
]

export type SetValidatorScoreInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _SetValidatorScore_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SetValidatorScore
 * @category generated
 */
export function createSetValidatorScoreInstruction(
  accounts: SetValidatorScoreInstructionAccounts,
  args: SetValidatorScoreInstructionArgs,
): SetValidatorScoreInstruction {
  const { state, managerAuthority, validatorList } = accounts

  const [data] = setValidatorScoreStruct.serialize({
    instructionDiscriminator: setValidatorScoreInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: managerAuthority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: validatorList,
      isWritable: true,
      isSigner: false,
    },
  ]

  const ix: SetValidatorScoreInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
