/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category StakeReserve
 * @category generated
 */
export type StakeReserveInstructionArgs = {
  validatorIndex: number
}
/**
 * @category Instructions
 * @category StakeReserve
 * @category generated
 */
export const stakeReserveStruct = new beet.BeetArgsStruct<
  StakeReserveInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['validatorIndex', beet.u32],
  ],
  'StakeReserveInstructionArgs',
)
/**
 * Accounts required by the _stakeReserve_ instruction
 *
 * @property [_writable_] state
 * @property [_writable_] validatorList
 * @property [_writable_] stakeList
 * @property [_writable_] validatorVote
 * @property [_writable_] reservePda
 * @property [_writable_] stakeAccount
 * @property [] stakeDepositAuthority
 * @property [] clock
 * @property [] epochSchedule
 * @property [] stakeHistory
 * @property [] stakeConfig
 * @property [] stakeProgram
 * @category Instructions
 * @category StakeReserve
 * @category generated
 */
export type StakeReserveInstructionAccounts = {
  state: web3.PublicKey
  validatorList: web3.PublicKey
  stakeList: web3.PublicKey
  validatorVote: web3.PublicKey
  reservePda: web3.PublicKey
  stakeAccount: web3.PublicKey
  stakeDepositAuthority: web3.PublicKey
  clock: web3.PublicKey
  epochSchedule: web3.PublicKey
  stakeHistory: web3.PublicKey
  stakeConfig: web3.PublicKey
  stakeProgram: web3.PublicKey
}

export const StakeReserveAccounts = [
  'state',
  'validatorList',
  'stakeList',
  'validatorVote',
  'reservePda',
  'stakeAccount',
  'stakeDepositAuthority',
  'clock',
  'epochSchedule',
  'stakeHistory',
  'stakeConfig',
  'stakeProgram',
]

export const stakeReserveInstructionDiscriminator = [
  87, 217, 23, 179, 205, 25, 113, 129,
]

export type StakeReserveInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _StakeReserve_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category StakeReserve
 * @category generated
 */
export function createStakeReserveInstruction(
  accounts: StakeReserveInstructionAccounts,
  args: StakeReserveInstructionArgs,
): StakeReserveInstruction {
  const {
    state,
    validatorList,
    stakeList,
    validatorVote,
    reservePda,
    stakeAccount,
    stakeDepositAuthority,
    clock,
    epochSchedule,
    stakeHistory,
    stakeConfig,
    stakeProgram,
  } = accounts

  const [data] = stakeReserveStruct.serialize({
    instructionDiscriminator: stakeReserveInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: state,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: validatorList,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: stakeList,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: validatorVote,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: reservePda,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: stakeAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: stakeDepositAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: clock,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: epochSchedule,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: stakeHistory,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: stakeConfig,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: stakeProgram,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix: StakeReserveInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
