/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category UpdateActive
 * @category generated
 */
export type UpdateActiveInstructionArgs = {
  stakeIndex: number
  validatorIndex: number
}
/**
 * @category Instructions
 * @category UpdateActive
 * @category generated
 */
export const updateActiveStruct = new beet.BeetArgsStruct<
  UpdateActiveInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['stakeIndex', beet.u32],
    ['validatorIndex', beet.u32],
  ],
  'UpdateActiveInstructionArgs',
)
/**
 * Accounts required by the _updateActive_ instruction
 *
 * @property [_writable_] stateCommonCommon
 * @property [_writable_] stakeListCommonCommon
 * @property [_writable_] stakeAccountCommonCommon
 * @property [] stakeWithdrawAuthorityCommonCommon
 * @property [_writable_] reservePdaCommonCommon
 * @property [_writable_] msolMintCommonCommon
 * @property [] msolMintAuthorityCommonCommon
 * @property [_writable_] treasuryMsolAccountCommonCommon
 * @property [] clockCommonCommon
 * @property [] stakeHistoryCommonCommon
 * @property [] stakeProgramCommonCommon
 * @property [] tokenProgramCommonCommon
 * @property [_writable_] validatorList
 * @category Instructions
 * @category UpdateActive
 * @category generated
 */
export type UpdateActiveInstructionAccounts = {
  stateCommonCommon: web3.PublicKey
  stakeListCommonCommon: web3.PublicKey
  stakeAccountCommonCommon: web3.PublicKey
  stakeWithdrawAuthorityCommonCommon: web3.PublicKey
  reservePdaCommonCommon: web3.PublicKey
  msolMintCommonCommon: web3.PublicKey
  msolMintAuthorityCommonCommon: web3.PublicKey
  treasuryMsolAccountCommonCommon: web3.PublicKey
  clockCommonCommon: web3.PublicKey
  stakeHistoryCommonCommon: web3.PublicKey
  stakeProgramCommonCommon: web3.PublicKey
  tokenProgramCommonCommon: web3.PublicKey
  validatorList: web3.PublicKey
}

export const UpdateActiveAccounts = [
  'stateCommonCommon',
  'stakeListCommonCommon',
  'stakeAccountCommonCommon',
  'stakeWithdrawAuthorityCommonCommon',
  'reservePdaCommonCommon',
  'msolMintCommonCommon',
  'msolMintAuthorityCommonCommon',
  'treasuryMsolAccountCommonCommon',
  'clockCommonCommon',
  'stakeHistoryCommonCommon',
  'stakeProgramCommonCommon',
  'tokenProgramCommonCommon',
  'validatorList',
]

export const updateActiveInstructionDiscriminator = [
  4, 67, 81, 64, 136, 245, 93, 152,
]

export type UpdateActiveInstruction = {
  programId: web3.PublicKey
  keys: web3.AccountMeta[]
  data: Buffer
}

/**
 * Creates a _UpdateActive_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateActive
 * @category generated
 */
export function createUpdateActiveInstruction(
  accounts: UpdateActiveInstructionAccounts,
  args: UpdateActiveInstructionArgs,
): UpdateActiveInstruction {
  const {
    stateCommonCommon,
    stakeListCommonCommon,
    stakeAccountCommonCommon,
    stakeWithdrawAuthorityCommonCommon,
    reservePdaCommonCommon,
    msolMintCommonCommon,
    msolMintAuthorityCommonCommon,
    treasuryMsolAccountCommonCommon,
    clockCommonCommon,
    stakeHistoryCommonCommon,
    stakeProgramCommonCommon,
    tokenProgramCommonCommon,
    validatorList,
  } = accounts

  const [data] = updateActiveStruct.serialize({
    instructionDiscriminator: updateActiveInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: stateCommonCommon,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: stakeListCommonCommon,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: stakeAccountCommonCommon,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: stakeWithdrawAuthorityCommonCommon,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: reservePdaCommonCommon,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: msolMintCommonCommon,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: msolMintAuthorityCommonCommon,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: treasuryMsolAccountCommonCommon,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: clockCommonCommon,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: stakeHistoryCommonCommon,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: stakeProgramCommonCommon,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: tokenProgramCommonCommon,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: validatorList,
      isWritable: true,
      isSigner: false,
    },
  ]

  const ix: UpdateActiveInstruction = new web3.TransactionInstruction({
    programId: new web3.PublicKey('NONE'),
    keys,
    data,
  })
  return ix
}
